POST http://localhost:8080/api/user_books/add
Content-Type: application/json

{
  "user": {
    "name": "name",
    "surname": "surname",
    "patronymic": "patronymic",
    "dateOfBirth": "2020-10-10"
  },
  "book": {
    "title": "And Quiet Flows the Don",
    "author": "Mikhail Aleksandrovich Sholokhov",
    "genre": "Novel"
  },
  "dateTime": "2020-10-20 12:49:23.123+03:00"
}