create schema if not exists public;
create table author
(
    id          bigint generated by default as identity
        constraint author_pkey
            primary key,
    created     timestamp,
    updated     timestamp,
    version     bigint,
    first_name  varchar(255),
    last_name   varchar(255),
    middle_name varchar(255),
    birth_date  timestamp
);

alter table author
    owner to postgres;

create table book
(
    id               bigint generated by default as identity
        constraint book_pkey
            primary key,
    created          timestamp,
    updated          timestamp,
    version          bigint,
    library_date     date,
    name             varchar(255),
    publication_date date,
    author_id        bigint
        constraint fkklnrv3weler2ftkweewlky958
            references author
            on delete cascade
);

alter table book
    owner to postgres;

create table dim_genre
(
    id         bigint generated by default as identity
        constraint dim_genre_pkey
            primary key,
    created    timestamp,
    updated    timestamp,
    version    bigint,
    genre_name varchar(255)
);

alter table dim_genre
    owner to postgres;

create table book_genre_lnk
(
    genre_id bigint not null
        constraint fk9rwhvr7cn94kkx1h276yu00ej
            references dim_genre,
    book_id  bigint not null
        constraint fkh8ac0uerpyu0mjgmukn2ojp43
            references book,
    constraint book_genre_lnk_pkey
        primary key (book_id, genre_id)
);

alter table book_genre_lnk
    owner to postgres;

create table person
(
    id          bigint generated by default as identity
        constraint person_pkey
            primary key,
    created     timestamp,
    updated     timestamp,
    version     bigint,
    first_name  varchar(255),
    last_name   varchar(255),
    middle_name varchar(255),
    birth_date  date
);

alter table person
    owner to postgres;

create table library_card
(
    id           bigint generated by default as identity
        constraint library_card_pkey
            primary key,
    created      timestamp,
    updated      timestamp,
    version      bigint,
    turning_date timestamp,
    book_id      bigint
        constraint fk5sa3r45pychnbva5fqd8cw13m
            references book,
    person_id    bigint
        constraint fks5k6hnrslp3sceoy2il5j5ebp
            references person
);

alter table library_card
    owner to postgres;

create table library_user
(
    person_id bigint not null
        constraint library_user_pkey
            primary key
        constraint fk2q7khdn0ocuach58705ex2pmg
            references person,
    created   timestamp,
    updated   timestamp,
    version   bigint,
    login     varchar(255),
    password  varchar(255),
    role      varchar(255)
);

alter table library_user
    owner to postgres;
