


POST http://localhost:8080/api/authors/add
Content-Type: application/json

{
  "firstName" : "Владимир",
  "lastName" : "Маяковский",
  "middleName" : "Владимирович"
}

###

GET http://localhost:8080/api/authors/getAll

###

DELETE http://localhost:8080/api/authors/delete/1

###

POST http://localhost:8080/api/books/add
Content-Type: application/json

{
  "name" : "Нате!",
  "authorId" : "4",
  "genreIds" : ["1","2"]
}

###

POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "firstName" : "Анастасия",
  "lastName" : "Егорова",
  "middleName" : "Андреевна",
  "birthDate" : "16-12-1999"
}
